# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose
version:      0.03
version_from: lib/Rose.pm
installdirs:  site
requires:
    Rose::DateTime:                0.0131
    Rose::DB:                      0.02
    Rose::DB::Object:              0.06
    Rose::HTML::Objects:           0.021
    Rose::Object:                  0.013
    Rose::URI:                     0.012
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
