# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose
version:      0.013
version_from: lib/Rose.pm
installdirs:  site
requires:
    Rose::DateTime:                0
    Rose::HTML::Objects:           0
    Rose::Object:                  0
    Rose::URI:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
