# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose
version:      0.05
version_from: lib/Rose.pm
installdirs:  site
requires:
    Rose::DateTime:                0.0134
    Rose::DB:                      0.032
    Rose::DB::Object:              0.50
    Rose::HTML::Objects:           0.30
    Rose::Object:                  0.016
    Rose::URI:                     0.021
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
